name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      - name: Debug - Check build artifacts
        run: |
          echo "== JAR files =="
          ls -lh target/*.jar || echo "No JARs found"
          echo "== SQL files =="
          ls -lh src/main/resources/static/sql/*.sql || echo "No SQLs found"

      - name: Copy JAR & SQL files to EC2 manually
        run: |
          echo "$EC2_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          scp -i ec2_key.pem -o StrictHostKeyChecking=no \
            target/*.jar \
            src/main/resources/static/sql/*.sql \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app/
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Create start.sh script on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cat << EOF > /home/ubuntu/app/start.sh
            #!/bin/bash

            echo "서버 중지"
            pkill -f 'jar' || true
            sleep 2

            echo "SQL 실행"
            for file in /home/ubuntu/app/*.sql; do
              echo "Importing \$file"
              mysql -h ssafyhome.c562miqic0og.ap-southeast-2.rds.amazonaws.com -u ssafy -p'ssafy' ssafyhome < "\$file"
              if [ \$? -ne 0 ]; then
                echo " Failed to import \$file"
              fi
            done

            echo "서버 재시작"
            export SPRING_PROFILES_ACTIVE=prod
            nohup java -jar /home/ubuntu/app/*.jar > /home/ubuntu/app/log.txt 2>&1 < /dev/null &
            EOF

            chmod +x /home/ubuntu/app/start.sh

      - name: Run start.sh on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            /home/ubuntu/app/start.sh
