name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Debug - Check build artifacts
        run: |
          echo "== JAR files =="
          ls -lh target/*.jar || echo "No JARs found"
          echo "== SQL files =="
          ls -lh src/main/resources/static/sql/*.sql || echo "No SQLs found"

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "target/*.jar"
          target: /home/ubuntu/app

      - name: Copy SQL files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "src/main/resources/static/sql/*.sql"
          target: /home/ubuntu/app

      - name: Create start.sh script on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cat << 'EOF' > /home/ubuntu/app/start.sh
            #!/bin/bash

            echo "서버 중지"
            pkill -f 'jar' || true
            sleep 2

            echo "SQL 실행"
            FILES=(
              "dbschema(1).sql"
              "sale_schema(2).sql"
              "member_dump(3).sql"
              "board_dump(4).sql"
              "comment_dump(5).sql"
              "property_dump(6).sql"
              "property_etc_dump(7).sql"
            )

            SQL_DIR="/home/ubuntu/app/src/main/resources/static/sql"

            for file in "${FILES[@]}"; do
              echo "Importing $file"
              mysql -h ssafyhome.c562miqic0og.ap-southeast-2.rds.amazonaws.com -u ssafy -p'ssafy' ssafyhome < "$SQL_DIR/$file"
              if [ $? -ne 0 ]; then
                echo "❌ Failed to import $file"
              fi
            done

            echo "서버 재시작"
            export SPRING_PROFILES_ACTIVE=prod
            nohup java -jar /home/ubuntu/app/target/*.jar > /home/ubuntu/app/log.txt 2>&1 < /dev/null &
            EOF

            chmod +x /home/ubuntu/app/start.sh

      - name: Run start.sh on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/app
            ./start.sh
